---
title: "p8105_hw5_yo2336"
author: "Yoo Rim Oh"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(readxl)


theme_set(theme(legend.position = "bottom"))
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

# Problem 1 done during Office Hour

Load and clean data
```{r}
homicide_df = 
  read_csv("./data/homicide-data.csv", na = c("", "Unknown")) %>%
  mutate(city_state = str_c(city, state),
         resolution = case_when(
           disposition == "Closed without arrest" ~ "unsolved",
           disposition == "Open/No arrest" ~ "unsolved",
           disposition == "Closed by arrest" ~ "solved"
         )) %>%
  relocate(city_state) %>%
  filter(city_state != "TulsaAL")
```


Baltimore

```{r}
baltimore_df =
  homicide_df %>% 
  filter(city_state == "BaltimoreMD")

baltimore_summary =
  baltimore_df %>%
  summarize(
    unsolved = sum(resolution == "unsolved"),
    n = n()
  )

baltimore_test = 
  prop.test(x = baltimore_summary %>% pull(unsolved),
            n = baltimore_summary %>% pull(n))

baltimore_test %>%
  broom::tidy()
```

Across all Cities

```{r}
prop_test_function = function(city_df) {
  
  city_summary =
    city_df %>%
    summarize(
      unsolved = sum(resolution == "unsolved"),
      n = n()
    )
  
  city_test = 
    prop.test(x = city_summary %>% pull(unsolved),
             n = city_summary %>% pull(n))

  return(city_test)
  
}

prop_test_function(baltimore_df)

homicide_df %>%
  filter(city_state == "AlbuquerqueNM") %>%
  prop_test_function()
```


```{r}
results_df =
  homicide_df %>%
  nest(data = uid:resolution) %>%
  mutate(
    test_results = map(data, prop_test_function),
    tidy_results = map(test_results, broom::tidy)
  ) %>%
  select(city_state, tidy_results) %>%
  unnest(tidy_results) %>%
  select(city_state, estimate, starts_with("conf"))
  
```

Plot

```{r}
results_df %>%
  mutate(city_state = fct_reorder(city_state, estimate)) %>%
  ggplot(aes(x = city_state, y = estimate)) +
  geom_point() +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high)) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))
```



# Problem 2

Iterate loading data and make data frame
```{r}
csv_file = 
  tibble(
  files = list.files("./data/long_study/"))

file_data =
  csv_file %>%
  map(~ read_csv(file.path("./data/long_study/", .))) %>%
  bind_cols()

study_df = 
  bind_cols(csv_file, file_data) %>%
  pivot_longer(
    week_1:week_8,
    names_to = "week",
    values_to = "observation"
  ) %>%
   rename(subject_id = files) %>%
   mutate(subject_id = str_replace(subject_id, ".csv", ""),
          arm = case_when(str_detect(subject_id, "^con") ~ "control",
                          str_detect(subject_id, "^exp") ~ "experimental"),
          week = str_replace(week, "week_", ""),
          week = as.numeric(week)) %>%
   relocate(subject_id, arm)

```


Plot
```{r}
study_df %>%
ggplot(aes(x = week, y = observation, color = subject_id)) +
  geom_point() +
  geom_line() +
  labs(title = "Distribution of Observations Over Time for Each Subject")
```

Control group generally has lower observation values as compared to the experimental group.


# Problem 3

Load data
```{r}
set.seed(10)

iris_with_missing = iris %>% 
  map_df(~replace(.x, sample(1:150, 20), NA)) %>%
  mutate(Species = as.character(Species))
```


Function to replace NA

```{r}
fill_in_missing = function(vector) {
 
  
   if (is.numeric(vector)) {
     new_vector = replace_na(vector, mean(vector, na.rm = TRUE))
  }
  
  
   if (is.character(vector)) {
     new_vector = replace_na(vector, "virginica")
  }
  
  return(new_vector)
}
```


Final dataframe with NA's replaced and check
```{r}
iris_filled =
  bind_cols(
    map(iris_with_missing, fill_in_missing))


summary(is.na(iris_with_missing))
summary(is.na(iris_filled))
```

